"""State 패턴의 추상 기반 클래스."""


class BaseState:
    def __init__(self, game) -> None:
        self.game = game

    def on_enter(self) -> None: ...
    def handle_event(self, event) -> None: ...
    def update(self, dt: float) -> None: ...
    def draw(self, surface) -> None: ...
